### ISSUE TITLE
multiple condition

### ISSUE THREAD

**Issue by maddin200** [unity8org/unity8org#1]
\plugins\Unity\InputInfo\linux\qinputdeviceinfo_linux.cpp line 179
if (i == EV_KEY || i == EV_SW || i == EV_REL <<<<
                || i == EV_REL || i == EV_ABS)

**Comment by KoczurekK** [comment]
Yep, clearly an issue, I'll fix it in a while.

**Comment by jsalatas** [comment]
closed by pull request
