### ISSUE TITLE
why all issues end jsalatas to ask to close the issue;

### ISSUE THREAD

**Issue by lepidas** [unity8org/unity8org#10]
jsalatas
commented about 1 hour ago

Agree with that. Can we please discuss it at the mailing list? :)

**Comment by jsalatas** [comment]
It's just a proposal to move the general discussions to a mailing list and leave github for reporting software related issues (bugs, wishes, etc).  

If you prefer we can continue all discussions here. :)

**Comment by lben** [comment]
Yes, as I said on another issue I don't get why mailing lists can be preferred over github issues. Most likely I am missing something but I don't know what. 

Nevertheless I congratulate jsalatas for using github instead of something like launchpad

**Comment by jsalatas** [comment]
IMHO Github is good for tracking software related issues. If we have general discussions in github, so these at some point close? Or remain open indefinitely and create a mess with all these open issues?

**Comment by lben** [comment]
I get you. That is likely to happend, no problem then, I think I will need to get used to use mailing lists and organize them on my mail account.
